CREATE USER 'tagger'@'localhost' IDENTIFIED BY  'tagger';

GRANT ALL PRIVILEGES ON * . * TO  'tagger'@'localhost' IDENTIFIED BY  'tagger' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS  `tagger` ;